package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePerson<M extends BasePerson<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPersonCategory(java.lang.Integer personCategory) {
		set("person_category", personCategory);
	}

	public java.lang.Integer getPersonCategory() {
		return get("person_category");
	}

	public void setPersonType(java.lang.Integer personType) {
		set("person_type", personType);
	}

	public java.lang.Integer getPersonType() {
		return get("person_type");
	}

	public void setPersonState(java.lang.Integer personState) {
		set("person_state", personState);
	}

	public java.lang.Integer getPersonState() {
		return get("person_state");
	}

	public void setPersonName(java.lang.String personName) {
		set("person_name", personName);
	}

	public java.lang.String getPersonName() {
		return get("person_name");
	}

	public void setPersonNumber(java.lang.String personNumber) {
		set("person_number", personNumber);
	}

	public java.lang.String getPersonNumber() {
		return get("person_number");
	}

	public void setPersonPhone(java.lang.String personPhone) {
		set("person_phone", personPhone);
	}

	public java.lang.String getPersonPhone() {
		return get("person_phone");
	}

	public void setPersonAddress(java.lang.String personAddress) {
		set("person_address", personAddress);
	}

	public java.lang.String getPersonAddress() {
		return get("person_address");
	}

	public void setPersonCompany(java.lang.String personCompany) {
		set("person_company", personCompany);
	}

	public java.lang.String getPersonCompany() {
		return get("person_company");
	}

	public void setPersonTimea(java.util.Date personTimea) {
		set("person_timeA", personTimea);
	}

	public java.util.Date getPersonTimea() {
		return get("person_timeA");
	}

	public void setPersonTimeb(java.util.Date personTimeb) {
		set("person_timeB", personTimeb);
	}

	public java.util.Date getPersonTimeb() {
		return get("person_timeB");
	}

	public void setPersonJob(java.lang.Integer personJob) {
		set("person_job", personJob);
	}

	public java.lang.Integer getPersonJob() {
		return get("person_job");
	}

	public void setPersonDisability(java.lang.String personDisability) {
		set("person_disability", personDisability);
	}

	public java.lang.String getPersonDisability() {
		return get("person_disability");
	}

	public void setPersonSecurity(java.lang.String personSecurity) {
		set("person_security", personSecurity);
	}

	public java.lang.String getPersonSecurity() {
		return get("person_security");
	}

	public void setPersonRemark(java.lang.String personRemark) {
		set("person_remark", personRemark);
	}

	public java.lang.String getPersonRemark() {
		return get("person_remark");
	}

	public void setPersonChildnum(java.lang.Integer personChildnum) {
		set("person_childNum", personChildnum);
	}

	public java.lang.Integer getPersonChildnum() {
		return get("person_childNum");
	}

	public void setPersonRemainmonth(java.lang.Integer personRemainmonth) {
		set("person_remainMonth", personRemainmonth);
	}

	public java.lang.Integer getPersonRemainmonth() {
		return get("person_remainMonth");
	}

	public void setSpouseState(java.lang.Integer spouseState) {
		set("spouse_state", spouseState);
	}

	public java.lang.Integer getSpouseState() {
		return get("spouse_state");
	}

	public void setSpouseName(java.lang.String spouseName) {
		set("spouse_name", spouseName);
	}

	public java.lang.String getSpouseName() {
		return get("spouse_name");
	}

	public void setSpouseNumber(java.lang.String spouseNumber) {
		set("spouse_number", spouseNumber);
	}

	public java.lang.String getSpouseNumber() {
		return get("spouse_number");
	}

	public void setSpouseCompany(java.lang.String spouseCompany) {
		set("spouse_company", spouseCompany);
	}

	public java.lang.String getSpouseCompany() {
		return get("spouse_company");
	}

	public void setSpouseTime(java.util.Date spouseTime) {
		set("spouse_time", spouseTime);
	}

	public java.util.Date getSpouseTime() {
		return get("spouse_time");
	}

	public void setSpouseRemark(java.lang.String spouseRemark) {
		set("spouse_remark", spouseRemark);
	}

	public java.lang.String getSpouseRemark() {
		return get("spouse_remark");
	}

	public void setChild1State(java.lang.Integer child1State) {
		set("child1_state", child1State);
	}

	public java.lang.Integer getChild1State() {
		return get("child1_state");
	}

	public void setChild1Name(java.lang.String child1Name) {
		set("child1_name", child1Name);
	}

	public java.lang.String getChild1Name() {
		return get("child1_name");
	}

	public void setChild1Number(java.lang.String child1Number) {
		set("child1_number", child1Number);
	}

	public java.lang.String getChild1Number() {
		return get("child1_number");
	}

	public void setChild1Company(java.lang.String child1Company) {
		set("child1_company", child1Company);
	}

	public java.lang.String getChild1Company() {
		return get("child1_company");
	}

	public void setChild1Time(java.util.Date child1Time) {
		set("child1_time", child1Time);
	}

	public java.util.Date getChild1Time() {
		return get("child1_time");
	}

	public void setChild1Remark(java.lang.String child1Remark) {
		set("child1_remark", child1Remark);
	}

	public java.lang.String getChild1Remark() {
		return get("child1_remark");
	}

	public void setChild2State(java.lang.Integer child2State) {
		set("child2_state", child2State);
	}

	public java.lang.Integer getChild2State() {
		return get("child2_state");
	}

	public void setChild2Name(java.lang.String child2Name) {
		set("child2_name", child2Name);
	}

	public java.lang.String getChild2Name() {
		return get("child2_name");
	}

	public void setChild2Number(java.lang.String child2Number) {
		set("child2_number", child2Number);
	}

	public java.lang.String getChild2Number() {
		return get("child2_number");
	}

	public void setChild2Company(java.lang.String child2Company) {
		set("child2_company", child2Company);
	}

	public java.lang.String getChild2Company() {
		return get("child2_company");
	}

	public void setChild2Time(java.util.Date child2Time) {
		set("child2_time", child2Time);
	}

	public java.util.Date getChild2Time() {
		return get("child2_time");
	}

	public void setChild2Remark(java.lang.String child2Remark) {
		set("child2_remark", child2Remark);
	}

	public java.lang.String getChild2Remark() {
		return get("child2_remark");
	}

	public void setChild3State(java.lang.Integer child3State) {
		set("child3_state", child3State);
	}

	public java.lang.Integer getChild3State() {
		return get("child3_state");
	}

	public void setChild3Name(java.lang.String child3Name) {
		set("child3_name", child3Name);
	}

	public java.lang.String getChild3Name() {
		return get("child3_name");
	}

	public void setChild3Number(java.lang.String child3Number) {
		set("child3_number", child3Number);
	}

	public java.lang.String getChild3Number() {
		return get("child3_number");
	}

	public void setChild3Company(java.lang.String child3Company) {
		set("child3_company", child3Company);
	}

	public java.lang.String getChild3Company() {
		return get("child3_company");
	}

	public void setChild3Time(java.util.Date child3Time) {
		set("child3_time", child3Time);
	}

	public java.util.Date getChild3Time() {
		return get("child3_time");
	}

	public void setChild3Remark(java.lang.String child3Remark) {
		set("child3_remark", child3Remark);
	}

	public java.lang.String getChild3Remark() {
		return get("child3_remark");
	}

	public void setChild4State(java.lang.Integer child4State) {
		set("child4_state", child4State);
	}

	public java.lang.Integer getChild4State() {
		return get("child4_state");
	}

	public void setChild4Name(java.lang.String child4Name) {
		set("child4_name", child4Name);
	}

	public java.lang.String getChild4Name() {
		return get("child4_name");
	}

	public void setChild4Number(java.lang.String child4Number) {
		set("child4_number", child4Number);
	}

	public java.lang.String getChild4Number() {
		return get("child4_number");
	}

	public void setChild4Company(java.lang.String child4Company) {
		set("child4_company", child4Company);
	}

	public java.lang.String getChild4Company() {
		return get("child4_company");
	}

	public void setChild4Time(java.util.Date child4Time) {
		set("child4_time", child4Time);
	}

	public java.util.Date getChild4Time() {
		return get("child4_time");
	}

	public void setChild4Remark(java.lang.String child4Remark) {
		set("child4_remark", child4Remark);
	}

	public java.lang.String getChild4Remark() {
		return get("child4_remark");
	}

	public void setChild5State(java.lang.Integer child5State) {
		set("child5_state", child5State);
	}

	public java.lang.Integer getChild5State() {
		return get("child5_state");
	}

	public void setChild5Name(java.lang.String child5Name) {
		set("child5_name", child5Name);
	}

	public java.lang.String getChild5Name() {
		return get("child5_name");
	}

	public void setChild5Number(java.lang.String child5Number) {
		set("child5_number", child5Number);
	}

	public java.lang.String getChild5Number() {
		return get("child5_number");
	}

	public void setChild5Company(java.lang.String child5Company) {
		set("child5_company", child5Company);
	}

	public java.lang.String getChild5Company() {
		return get("child5_company");
	}

	public void setChild5Time(java.util.Date child5Time) {
		set("child5_time", child5Time);
	}

	public java.util.Date getChild5Time() {
		return get("child5_time");
	}

	public void setChild5Remark(java.lang.String child5Remark) {
		set("child5_remark", child5Remark);
	}

	public java.lang.String getChild5Remark() {
		return get("child5_remark");
	}

	public void setLocationId(java.lang.Integer locationId) {
		set("location_id", locationId);
	}

	public java.lang.Integer getLocationId() {
		return get("location_id");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return get("state");
	}

}
