package com.wts.entity.model;

import com.wts.entity.base.BaseCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Category extends BaseCategory<Category> {
	public static final Category dao = new Category().dao();
}
