package com.wts.entity.model;

import com.wts.entity.base.BaseOperate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Operate extends BaseOperate<Operate> {
	public static final Operate dao = new Operate().dao();
}
