package com.wts.entity.model;

import com.wts.entity.base.BaseState;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class State extends BaseState<State> {
	public static final State dao = new State().dao();
}
